Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -112,9 +112,9 @@ jobs:
           flake8 $module
           if [ "$?" = "0" ]; then echo "Flake8 ok"; else echo "Flake8 error"; exit $exit_code; fi
           # black
-          echo Running: black --check $module
-          black --check $module
-          if [ "$?" = "0" ]; then echo "Black ok"; else echo "Black error"; exit $exit_code; fi
+          # echo Running: black --check $module
+          # black --check $module
+          # if [ "$?" = "0" ]; then echo "Black ok"; else echo "Black error"; exit $exit_code; fi
           # mypy
           # echo Running: mypy $module
           # mypy $module
